name: Rust CI

on:
  workflow_call: 
    outputs:
      ci_status:
        description: "Estado del CI: éxito o fallo"
        value: ${{ jobs.format.result && jobs.build.result }}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check code formatting
      run: cargo fmt --check --verbose
    - name: Lint code
      run: cargo clippy -- -D warnings



  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose